/// Generated by AssetsRefGenerator on 2020/10/27
class Res {
  static const String ball1 = "assets/images/ball1.png";
  static const String ball2 = "assets/images/ball2.png";
  static const String ball3 = "assets/images/ball3.png";
  static const String ball4 = "assets/images/ball4.png";
  static const String ball5 = "assets/images/ball5.png";
}
